services:
  control:
    build: 
      context: .
      dockerfile: Dockerfile_control
    network_mode: host
    volumes:
      - ./controller:/app/controller
    ports:
      - 5000:5000
    environment:
      - ROS_DOMAIN_ID=1
  
  robot:
    build: 
      context: .
      dockerfile: Dockerfile_robot
    network_mode: host
    volumes:
      - ./robot:/app/robot
    environment:
      - ROS_DOMAIN_ID=1