services:
  control:
    build: 
      context: .
      dockerfile: Dockerfile_control
    # network_mode: host
    container_name: ros2_controller
    privileged: true            
    devices:
      - /dev/video0:/dev/video0  
      # - /dev/ttyUSB0:/dev/ttyUSB0 
      # - /dev/gpiomem:/dev/gpiomem 
      # - /dev/mem:/dev/mem         
    restart: always             
    volumes:
      - ./controller:/app/controller
    ports:
      - 5000:5000
    environment:
      - ROS_DOMAIN_ID=1
  
  robot:
    build: 
      context: .
      dockerfile: Dockerfile_robot
    # network_mode: host
    container_name: ros2_robot
    devices:
      - /dev/video0:/dev/video0 
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/gpiomem:/dev/gpiomem:rwm
      # - /dev/mem:/dev/mem        
    privileged: true
    device_cgroup_rules:
      - 'c 188:* rmw' 
      # - 'c 1:* rmw'
      - 'c 238:* rmw'
    group_add:
      - dialout 
      - gpio
    restart: always 
    volumes:
      - ./robot:/app/robot
      - /sys:/sys
    environment:
      - ROS_DOMAIN_ID=1
    ports:
      - 5001:5001
      - 5002:5002
      - 5003:5003
# networks:
  # default:
    # external: true