services:
  control:
    build: 
      context: .
      dockerfile: Dockerfile_control
    # network_mode: host
    privileged: true            
    devices:
      - /dev/video0:/dev/video0  
      # - /dev/ttyUSB0:/dev/ttyUSB0 
      # - /dev/gpiomem:/dev/gpiomem 
      # - /dev/mem:/dev/mem         
    restart: always             
    volumes:
      - ./controller:/app/controller
    ports:
      - 5000:5000
    environment:
      - ROS_DOMAIN_ID=1
  
  robot:
    build: 
      context: .
      dockerfile: Dockerfile_robot
    # network_mode: host
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
      - /dev/gpiomem:/dev/gpiomem  # Add GPIO memory access
      - /dev/mem:/dev/mem          # Optional, for low-level memory access
    privileged: true
    # entrypoint: >
    #   /bin/bash -c "source /app/.venv/bin/activate && cd /app/robot && source install/setup.bash && ros2 run robot_control ros2_controller"       
    restart: always 
    volumes:
      - ./robot:/app/robot
    environment:
      - ROS_DOMAIN_ID=1
    ports:
      - 5001:5001
      - 5002:5002
# networks:
  # default:
    # external: true